### ISSUE TITLE
Feature roadmap

### ISSUE THREAD

**Issue by alexandreCameron** [alexandreCameron/boar#50]
# Critical
1. re raise error
2. adapt eval to enable function definition
3. __source

# Nice
4. check if file exists
5. use rglob in folder search
6. handle display
7. handle close of plt.figures 
8. handle close of plotly.figure
9. tranform assert to have nice log

**Comment by bneigher** [comment]
just want to say that I absolute love this library, I use it in my python aws lambdas.  It makes for a great development experience and can run in the cloud without any trouble.  

one thing that would be nice is to be able to exit the notebook (like a return ?), perhaps this is already documented though
